[32m2023-10-30 12:46:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6f94b894-5886-4608-8413-b262d74a1428 - 9563 - LOGS_CAPTURED - Started capturing logs in process (pid: 9563).
[32m2023-10-30 12:46:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6f94b894-5886-4608-8413-b262d74a1428 - 9563 - knmi_uurgegevens - STEP_START - Started execution of step "knmi_uurgegevens".
[32m2023-10-30 12:46:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6f94b894-5886-4608-8413-b262d74a1428 - 9563 - knmi_uurgegevens - STEP_OUTPUT - Yielded output "result" of type "DataFrame". Warning! Type check failed.
[32m2023-10-30 12:46:02 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 6f94b894-5886-4608-8413-b262d74a1428 - 9563 - knmi_uurgegevens - STEP_FAILURE - Execution of step "knmi_uurgegevens" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "DataFrame". Description: Value of type <class 'NoneType'> failed type check for Dagster type DataFrame, expected value to be of Python type polars.dataframe.frame.DataFrame.

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 275, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 483, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 531, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 404, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
